version: "3.4"


services:
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - qa-api
  #     - qa-ui
  #   ports:
  #     - 7800:7800

  app-backend:
    build: ./app-backend
    ports:
      - "3000:3000"
    env_file:
      - project.env
    depends_on:
      - database
      - flyway
    restart: unless-stopped

  database:
    container_name: database-server-dab-p2-ffeb713a-b7eb-49df-a5ae-4877ceec8fdc
    image: postgres:14.1
    restart: "no"
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
