# 使用官方 Golang 镜像作为构建阶段
FROM golang:1.24 AS builder

# 设置工作目录
WORKDIR /app

# 复制 Go 模块文件
COPY go.mod go.sum ./

# 下载依赖
RUN go mod download

# 复制源代码
COPY . .

# 构建可执行文件
RUN go build -o server ./cmd/main.go

# 使用轻量级的基础镜像运行应用
FROM debian:bookworm-slim

# 设置工作目录
WORKDIR /app

# 复制构建好的可执行文件
COPY --from=builder /app/server .

# 运行服务器
CMD ["./server"]

# 监听端口
EXPOSE 3000
